
extends: standard
rules:
  operator-linebreak: [ error, before ]
  object-curly-spacing: [ error, always ]
  indent: [ error, 2, {
    flatTernaryExpressions: true
  }]
  padded-blocks: off
  space-in-parens: [ error, always ]
